# First draft that worked. With webdriverio and docker on windows
# docker network ls
# i believe need docker `network create grid`
# since i configured it to external
services:

  selenium-hub:
    container_name: selenium-hub
  # selenium: # standalone
    image: selenium/hub:latest
    # image: selenium/standalone-chrome:latest
    # https://hub.docker.com/r/selenium/standalone-chrome/tags
    # this image is hub... i used standalone in the other ones
    # apparently i just used 4 standalones lol
    networks:
      - grid
    # https://github.com/SeleniumHQ/docker-selenium/blob/trunk/Standalone/generate_config
    # standalone ignores a lot of the env variables
    environment:
      # https://github.com/SeleniumHQ/docker-selenium/blob/trunk/ENV_VARIABLES.md
      - GRID_MAX_SESSION=16
      - SE_VNC_NO_PASSWORD=1
    ports:
      - "4442-4444:4442-4444"
      # - "4444:4444"
      # - "7900:7900" # goes to node not the hub
    shm_size: 2g

  chrome:
  # https://hub.docker.com/r/selenium/node-chrome
  # novnc config goes here
    image: selenium/node-chrome:latest
    depends_on:
      - selenium-hub
    environment:
      # - HUB_HOST=selenium-hub # this needed?
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      # - SE_VNC_VIEW_ONLY=1
      - SE_VNC_NO_PASSWORD=1
      # bingo: grid url, but the port isnt going to be right?
      # - SE_NODE_GRID_URL=http://selenium-hub:4444 # try or maybe need to use ip or host.docker.internal
      - SE_NODE_GRID_URL=http://host.docker.internal:4444 # try or maybe need to use ip or host.docker.internal
      # might not want 4444 port for the node as well
    ports:
          - "7900:7900" # Expose noVNC port
      # 5555 probably here in the node
    networks:
      - grid
    shm_size: 2g
  chrome_1:
      # https://hub.docker.com/r/selenium/node-chrome
      # novnc config goes here
      image: selenium/node-chrome:latest
      depends_on:
        - selenium-hub
      environment:
        - SE_EVENT_BUS_HOST=selenium-hub
        - SE_EVENT_BUS_PUBLISH_PORT=4442
        - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
        - SE_VNC_NO_PASSWORD=1
        - SE_NODE_GRID_URL=http://host.docker.internal:4444 # try or maybe need to use ip or host.docker.internal
      ports:
        # modified here - maybe generate in the future
        - "7901:7900" # Expose noVNC port
      networks:
        - grid
      shm_size: 2g
networks:
  grid:
    name: grid
    external: true
